version: 3

tasks:
  CI:
    deps:
      - for:  [tokio, smol, glommio]
        task: test:rt
        vars: { rt: '{{.ITEM}}' }
      - task: test:no_rt
      - task: test:doc

  test:rt:
    cmds:
      - cargo test --lib --features rt_{{.rt}}
      - cargo test --lib --features rt_{{.rt}},tcpstream-only

  test:no_rt:
    cmds:
      - cargo test

  test:doc:
    cmds:
      - cargo test --doc --features rt_tokio,DEBUG
