version: 3

tasks:
  CI:
    deps:
      - for:  [tokio, futures]
        task: test:with_io
        vars: { io: '{{.ITEM}}' }
      - task: test:without_io
      - task: test:doc

  test:with_io:
    cmds:
      - cargo test --lib --features io_{{.io}}

  test:without_io:
    cmds:
      - cargo test

  test:doc:
    cmds:
      - cargo test --doc --features io_tokio
