name: Publish

on:
  push:
    tags: [v*]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    environment:
      name: publishing
      
    permissions:
      contents: write # to create releases
    
    steps:
      - uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0
      
      - name: Ensure main branch
        run: |
          BRANCHS=$(git branch --contains ${{ github.ref_name }})
          set -- $BRANCHS
          for BRANCH in $BRANCHS ; do
            if [[ "$BRANCH" == "main" ]]; then
              exit 0
            fi
          done
          exit 1
      
      - uses: rust-lang/crates-io-auth-action@v1
        id: cratesio_auth
      
      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.cratesio_auth.outputs.token }}
        run: |
          cargo publish --package mews
      
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} --generate-notes
